#!/bin/bash

cd /tablut/TablutAI/Tablut

if [ "$1" == "WHITE" ];then
	ant whiteFailureState
elif [ "$1" == "BLACK" ];then
	ant blackFailureState
else
	echo "You should specify as the first parameter the color of the player in upper case";
fi
